nelmio_api_doc:
    documentation:
        info:
            title: Wikimedia OCR
            description: A web service for Kraken, Tesseract, Google and Transkribus OCR engines.
            version: 1.2.1
    areas:
        path_patterns:
            - ^/api$
            - ^/api/available_langs$
            - ^/api/transkribus/available_line_ids$
