image: debian:bookworm

variables:
  APP_ENV: test

ocr-test:
  stage: test
  script:
    - |
      apt update -q
      apt install -y curl php php-imagick php-ast php-bcmath php-curl php-gd php-dom php-intl php-simplexml php-xml tesseract-ocr-all nodejs npm
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install
      npm ci
      php composer.phar test
      npm run test
      npm run build
      git status
      git status | grep "nothing added to commit"
  artifacts:
    when: on_failure
    paths:
      - ./var/log/test.log
